name: Smart-Contract tests
on: ["push", "pull_request"]

jobs:
  coverage:
    name: Run solidity-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Prepare dependencies
        run: yarn install
          
      - name: Compile & generate artifacts
        run: npm run generate-artifacts

      - name: Run truffle coverage
        run: npm run coverage

      - name: Push results to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage/lcov.info
  
  run-tests:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Prepare dependencies
        run: yarn install
          
      - name: Run ganache
        run: npx ganache-cli & sleep 5 #runs ganache in background and wait 5 seconds for it to start up

      - name: Run tests
        run: yarn test
